### ISSUE TITLE
Support Logging Autosetup

### ISSUE THREAD

**Issue by dploeger** [esatterwhite/node-seeli#3]
*(Background: I'm currently migrating my CLI apps from Python/[Cement](builtoncement.com) to NodeJs/Seeli)*

It would be great, if common logging parameters for CLI apps would be interpreted and the app can log directly without setting it up.

For example:
```
./cli.js
```
=> Loglevel set to **Warn**

```
./cli.js -v
```
=> Loglevel set to **Info**

```
./cli.js -d
```

=> Loglevel set to **Debug**

The logger could be inside the data object, that is given to the run-methods:

```
(...)
run: function (name, data, done) {
  data.log.debug("Starting command %s", name);
  (...)
}
(...)
```

I would suggest to rely on [Winston](https://github.com/winstonjs/winston) for logging purposes.

**Comment by esatterwhite** [comment]
I like winston, and tend to use it on most of my projects. But I think logging in general is out side the scope of this project. Personally, I use nconf to pass configuration into winston, which can be done via the command line because seeli doesn't mess with `process.argv`. 

[This](http://www.codedependant.net/2015/03/05/production-ready-node-logging/) is basically the setup

**Comment by esatterwhite** [comment]
Closing this one. Just out side the scope of the project.

You could also decorate the seeli object your self. `seeli.set('log', require('winston') )` and attach methods the way you like.

Its not a bad idea, just not the place for it.

**Comment by dploeger** [comment]
You're right. Perhaps I just make a node module, that wraps around winston and sets it up based on common arguments.
